---
name: 'CI'

'on':
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'

jobs:
  ci:
    name: 'CI (${{ matrix.python-version }})'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - name: 'Install just'
        run: 'sudo apt install just'
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
        with:
          persist-credentials: false
      - name: 'Setup uv with python ${{ matrix.python-version }}'
        uses: 'astral-sh/setup-uv@v7.2.0'
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: '${{ matrix.python-version }}'
      - name: 'Run Checks'
        run: 'just ci'
        env:
          UV_PYTHON_VERSION: '${{ matrix.python-version }}'
  docs:
    name: 'Docs (${{ matrix.python-version }})'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.12'
    steps:
      - name: 'Install just'
        run: 'sudo apt install just'
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
        with:
          persist-credentials: false
      - name: 'Setup uv'
        uses: 'astral-sh/setup-uv@v7.2.0'
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: '${{ matrix.python-version }}'
      - name: 'Build Documentation'
        run: 'just docs'
        env:
          UV_PYTHON_VERSION: '${{ matrix.python-version }}'
